---
title: "LSDIM: investigating specific simulations"
author: "Thibaut Jombart"
output:
  html_document: 
    toc: true
    toc_depth: 3
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  collapse = TRUE, 
  fig.width = 8, 
  fig.height = 6, 
  dpi = 70
  )
```

```{r}
library(tidyverse)
library(qs)
library(here)
```


## Outline of the work

We analyse specific simulations to understand outcomes of interests.




### Why do some simulations go large?

Specifically, we try and understand how some (rare) simulations in the **sellcull_quarant_vacc** scenario go really large, apparently against all odds.

```{r}
all_files <- list.files(here::here("outputs"), pattern = "^res")
extract_date <- function(x) {
  out <- gsub("[^[:digit:]-]", "", x)
  as.Date(out)
}
dates <- sapply(all_files, extract_date)
to_keep <- which.max(dates)
file_to_keep <- all_files[to_keep]
file_to_keep
message("reading results from file:", file_to_keep)
res <- qread(here::here("outputs", file_to_keep))

sims_to_check <- res %>% 
  filter(scenario == "selcull_quarant_vacc", total_cases > 1e4) %>% 
  pull(label)
sims_to_check 
```



```{r}
sim_dir <- here::here("outputs", "simulations", 
                      "selcull_quarant_vacc", "2025-12-21")
all_files <- list.files(
  sim_dir, 
  pattern = paste(sims_to_check[1], "selcull", sep = "_"), 
  full = TRUE)
all_files
```

We open files one at a time to check outbreak sizes
```{r}
sims <- lapply(all_files, qread)
smrys <- lapply(sims, summary)
```

Investigation of the first simulation:
```{r}
I <- sims[[1]][,grep("^I", colnames(sims[[1]]))]
id_ini_inf <- which(I[1,] > 0)
to_keep <- paste(
  c("S", "E", "new_I", "I", "R", "C", "D", "V", "status"), 
  id_ini_inf, 
  sep = "_"
)

ini_patch <- sims[[1]][, to_keep]
```



